CREATE TABLE simpleproduct_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price INT NOT NULL,
    logo TEXT NOT NULL,
    weight INT NOT NULL,
    lenght INT NOT NULL,
    diameter INT NOT NULL,
    images TEXT[] NOT NULL,
    details TEXT NOT NULL
);